dist: xenial
language: python
services:
  - postgresql
python:
  - "3.7"
cache: pip
install:
  - pip install -r requirements.txt
script:
  - py.test --cov-report term-missing --cov app -v
deploy:
  provider: heroku
  api_key:
    secure: ""
  app: sos-shoppingcart
